### ISSUE TITLE
Question: Extending this framework

### ISSUE THREAD

**Issue by Close0** [jjkester/django-auditlog#114]
Hello there, I want to start off being that this is not an issue as much as a question.

For my project I'm looking for something very similar to this framework. However I'm wanting to add some additional fields to the table such as a human readable string and some other project specific fields.

Do you have any suggestions on how best to achieve this aside from forking the project? Such as extending the model and middleware etc?

**Comment by audiolion** [comment]
check my pr

https://github.com/jjkester/django-auditlog/pull/94

I implemented human readable strings

**Comment by jjkester** [comment]
You can let your models define a method `get_additional_data`, of which the return value is serialized to JSON and put in the database. An example can be seen in the tests: https://github.com/jjkester/django-auditlog/blob/v0.4.3/src/auditlog_tests/models.py#L87

It seems that this feature is not documented at this point, so that is something that should be improved.
