### ISSUE TITLE
Support Django 1.4

### ISSUE THREAD

**Issue by mario-viasto** [jjkester/django-auditlog#19]
What prevents the app to work on Django 1.4? As far as I could see it's all about the customisable AUTH_USER_MODEL, right? If so, it could be done by setting manually with minor changes.

The point is: I am working in a big project based on Django 1.4 so, I'd rather do this effort on adapting it to support 1.4 too than going through the whole project and upgrading it to 1.5 only because of that.

**Comment by jjkester** [comment]
I think the only issue is indeed the custom user model. I started working on this app when 1.5 was the latest release so I kind of just stuck with it.

I don't think that the migrations need to be adapted as these are Django 1.7-style migrations, not South migrations, but it should not do any harm.

Did you test your code with Django 1.4, and if not, could you?

**Comment by mario-viasto** [comment]
Yes, I tested, but it's actually more behind it. The code relying on "instance._meta.model" is raising an error like "Options" has no attribute "model", which I got no time to investigate any deeper, so, it could be something specific on my project or something to Django 1.4. I gonna check more and respond soon.

Thanks

**Comment by mario-viasto** [comment]
Well, the thing with "Options" object is actually easy to solve, but migrations is the complicated one.

What do you suggest then? The actual option I have now is to adapt my fork for Djanto 1.4 and remove migrations module from it to let it work. Any better insight?

**Comment by jjkester** [comment]
Can't you just ignore the migrations? Or is South complaining that there is a migrations module, but that the migrations in it are not valid?

**Comment by philippeowagner** [comment]
Why not use https://github.com/arteria/django-compat for back- and forward compatibility?

**Comment by jjkester** [comment]
@philippeowagner One of the key benefits of this library is the small footprint and lack of dependencies - I like to keep it that way.

Furthermore, to get back on topic about specifically 1.4, I know it is an LTS release and it is still supported by the Django team. However, due to major compatibility issues (in general, not only the ones discussed in this thread) with 1.5, 1.6 and especially 1.7 and 1.8 I am not compelled to backport the library myself. However, the license allows you to fork the project and backport it yourself. I am happy to provide a reference to your backported fork, but I have decided to not include support for 1.4 and Django versions that are currently not supported.

After all, this project is still in development and far from production ready. Considering the amount of time I have available and the progress on this project I simply cannot justify the work.
