### ISSUE TITLE
Object representation is missing in update operation, instead it showing username

### ISSUE THREAD

**Issue by shashank9487** [jjkester/django-auditlog#51]
The problem is when i make any update operation on any model then random thing happen like **username** field shows None and and **object representation** field shows username instead in django admin. I go through the code but all is going good with signals and create/update operations

**Comment by jjkester** [comment]
Can you tell me what exact versions you are using (Python, Django, django-auditlog) and how you create log entries (automatically, manually using your own signals, etc.)?

There are many cases in which the `actor` field is not populated automatically, however, it does not seem likely that the `object_repr` field shows an incorrect value.

It is interesting that you mention the Django admin since Auditlog does not come with Django Admin integration by default, can you explain how you implemented this?

**Comment by shashank9487** [comment]
My stack is 

`python 2.7`
`Django 1.8.4`
`django-auditlog==0.3.2`

I am using only default auditlog, no custom signals and all. Just execute it by `auditlog.register(ExceptionLogs)`.

**And in admin, what i am doing is:**

`from auditlog.models import LogEntry as CustomLogEntry`

`class LogEntryAdmin(admin.ModelAdmin):`
	`"""docstring for LogEntryAdmin"""`

	readonly_fields = CustomLogEntry._meta.get_all_field_names()
	search_fields = ('object_repr', 'changes',)
	list_display = ('actor_id', 'changes', 'action', 'object_repr', 'timestamp')
	ordering = ['-timestamp']

	def has_add_permission(self, request):
		return False

`admin.site.register(CustomLogEntry, LogEntryAdmin)`

**Comment by shashank9487** [comment]
Hello,

Anything good for me ?. I need to resolve this issue soon as i can.

**Comment by jjkester** [comment]
Hi,

I have not been able to make time to look at this properly. I understand that this issue is not ideal. However, from a *theorethical* view, it should work. I will have to try and reproduce this in order to see where this error occurs.

Since I have to maintain this package in my free time, which is limited (and I also want to do other things beside coding), updates might take some time. However, I can promise you that I won't discard this issue and I will take a proper look at it, I just cannot promise you when. Thanks for understanding.

**Comment by jjkester** [comment]
Hi,

I have been unable to reproduce your issue. Both the actual database record and the representation in the Django Admin are correct for me. Can you check the records in your database, are those correct? What happens when you don't use a custom Admin class and you just call ```admin.site.register(CustomLogEntry)```?

**Comment by jjkester** [comment]
Closed because the OP did not respond in a timely manner.
