### ISSUE TITLE
Data in 'changes' field is unicode-escaped

### ISSUE THREAD

**Issue by belidzs** [jjkester/django-auditlog#53]
I'm using django-auditlog with python 2.7.6 and django 1.9. 

My source files are encoded with utf-8, so there is a `# coding=utf-8` statement in the first lines. I have also imported `unicode_literals` from `__future__`

The issue is that while `Logentry.changes` correctly stores the changes in my data, every accented character is converted to escaped unicode characters before saving. I can workaround this issue with a simple `get_queryset()` override, but maybe letting django convert special characters would be a more elegant solution.

Here is my workaround code:

```python
# coding=utf-8
from __future__ import unicode_literals

..

class AuditView(generic.ListView):
    model = LogEntry

    def get_queryset(self):
        result = LogEntry.objects.get_for_model(Kod)
        for row in result:
            row.changes = row.changes.decode('unicode-escape')
        return result
```

**Comment by jjkester** [comment]
I really have to look into this. Using some `six` compatibility tools and the `unicode_literals` import *should* (when used properly) ensure that all is unicode on Python 2.7 (with Python 3 all strings are unicode by default).

Personally I have not specified the coding of the files, do you still have problems when you temporarily remove the coding statement?

**Comment by belidzs** [comment]
I can't remove `# coding=utf-8` as my source code contains accented characters (literals, comments, etc)

However, I removed the import, but auditlog behaves exactly the same.

**Comment by jjkester** [comment]
Thanks for the quick reply. I'll look at this soon.

**Comment by jjkester** [comment]
You are using `LogEntry.changes` directly, which can be done. However, Python 2.7s JSON encoder has done some things to this string to preserve unicode data in a non-unicode environment. `LogEntry.changes_dict` will deserialize the JSON-encoded data in `LogEntry.changes`. The resulting strings are all unicode and the special characters seem to be encoded/decoded correctly.

Could you try using this method instead of `LogEntry.changes` directly? If this does not work, can you tell me:

- What database are you using?
- What is the encoding of your database (tables/fields)?
- What is an example of input (the calculated changes dictionary of an object) and its corresponding output?

**Comment by jjkester** [comment]
Of course I would like to hear whether this issue is resolved.

**Comment by belidzs** [comment]
Hi! I will let you know as soon as I will be able to test the suggested
test cases, but right now I'm a bit short on time. Thanks for the patience!

On Tue, May 17, 2016 at 10:03 AM, Jan-Jelle Kester <notifications@github.com

**Comment by belidzs** [comment]
Today I had time to try your suggestions. 

Seems like using `LogEntry.changes_dict` instead of `LogEntry.changes` resolves this issue completely. What's even better, I realized that I could've just used changes_str all along to display the changes on a web page. Shame on me for not reading the docs carefully.

Thanks for your help!
