### ISSUE TITLE
Purge logs

### ISSUE THREAD

**Issue by exp0nge** [jjkester/django-auditlog#56]
Is the only way to purge logs to manually go in and delete the objects?

**Comment by jjkester** [comment]
At the moment, yes. With the shell this can be quite easily done, but a management command would be nice to have I guess (and is not that hard to make). It is going on the feature list.

Only purging a selection of entries is not as easy and will probably never will be (since everyone has different requirements this would be unnecessarily complex). You can always create your own views or commands for that purpose of course.
